kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitor-sa
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 1m
      smtp_smarthost: 'smtp.163.com:25'
      smtp_from: '17714498421@163.com'
      smtp_auth_username: '17714498421@163.com'
      smtp_auth_password: 'PURLEEMOSRYNZIBR'
      smtp_require_tls: false
    route:
      group_by: [alertname]
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 5m
      receiver: default-receiver
    receivers:
    - name: 'default-receiver'
      email_configs:
      - to: '2580129386@qq.com'
        send_resolved: true

